spring.application.name=portfolio

# Email Configuration (Uses Render Environment Variables with default fallbacks)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=vickyarsvicky@gmail.com
spring.mail.password=vlsz dpbf cvil zobu

# SSL Properties for Port 465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false
